### ISSUE TITLE
Make map size a configurable css variable

### ISSUE THREAD

**Issue by morganecf** [morganecf/jitsi-party#512]
This is to avoid situations like the one in https://github.com/morganecf/jitsi-party/pull/513 where we hardcode the map proportions to fit certain map designs.

**Comment by rene-grigory** [comment]
@morganecf, I'm looking at the code and I see that the **width** and **height** are being passed to the **MapVisualization** component which generates the SVG. The **d3** utility that generates the SVG uses the **width/height** along with the **padding** value to perform a linear scaling. It may be easier to make the height and width ratios config settings instead of replacing everything with CSS.

Something like the following: 
```
{
  mapSizeRatio: {
    width: 2.5,
    height: 1.25
  }
}
```

**Comment by rene-grigory** [comment]
I can take care of it.
